ItiBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: ItiBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        restauration:
            type: string
            length: '100'
        patrimoineCulturel:
            type: string
            length: '100'
            column: patrimoine_culturel
        equipement:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
